Blog/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'Blog'

urlpatterns = [
    # Главная страница блога
    path('', views.BlogHomeView.as_view(), name='index'),
    
    # Редирект для совместимости
    path('index.html', RedirectView.as_view(url='/blog/', permanent=True)),
    
    # Посты
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:slug>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    
    # Категории
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    
    # Теги
    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('tag/<slug:slug>/', views.TagDetailView.as_view(), name='tag_detail'),
    path('tag/<str:tag>/', views.TaggedPostsView.as_view(), name='tagged_posts'),
    
    # Профили пользователей
    path('user/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    
    # AJAX действия
    path('ajax/like/', views.toggle_like, name='toggle_like'),
    path('ajax/follow/', views.toggle_follow, name='toggle_follow'),
    path('ajax/comment/', views.add_comment, name='add_comment'),
    
    # Подписка на рассылку
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
    
    # Аутентификация
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.register_view, name='register'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('author-request/', views.author_request_view, name='author_request'),
]

Home/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'Home'

urlpatterns = [
    path('', home, name='home'),
    #path('', PostListView.as_view(), name='blog'),
    #path('blog/', PostListView.as_view(), name='blog'),
    #path('post/create/', PostCreateView.as_view(), name='post_create'),
    #path('post/<str:slug>/', post_detail, name='post_detail'),
    #path('post/<str:slug>/update/', PostUpdateView.as_view(), name='post_update'),
    #path('post/<str:slug>/delete/', PostDeleteView.as_view(), name='post_delete'),
    #path('category/<str:slug>/', PostByCategoryListView.as_view(), name="post_list_by_category"),
    #path('post/tags/<str:tag>/', PostByTagListView.as_view(), name='post_by_tags'),
    #path('author/<str:slug>/', AutorPostListView.as_view(), name='autor'),
    #path('post/author/<str:author>/', PostByAutorListView.as_view(), name='post_by_author'),
    
]

NLPers/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView

# Импортируем настройки админки
from . import admin as admin_config

urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('Blog.urls', namespace='Blog')),
    path('archive/', include('Archive.urls', namespace='Archive')),
    path('', include('Home.urls', namespace='Home')),
    
    # Redirects for compatibility with old URLs
    path('blog.html', RedirectView.as_view(url='/blog/', permanent=True)),
    path('blog-details.html', RedirectView.as_view(url='/blog/', permanent=True)),
    path('index.html', RedirectView.as_view(url='/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/meny/foser.html
{% load static %}
<!-- footer-area -->
<footer>
    <div class="footer-top-wrap">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-xl-3 col-lg-4 col-md-5 col-sm-9">
                    <div class="footer-widget">
                        <div class="footer-logo mb-25">
                            <a href="index.html"><img src="{% static 'nlp/img/logo/logo.png' %}" alt=""></a>
                        </div>
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Natus veritatis sequi doloribus fuga.</p>
                        <ul class="footer-social">
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer-widget">
                        <h4 class="fw-title">Useful Links</h4>
                        <ul class="fw-links">
                            <li><a href="nft-marketplace.html">All NFTs</a></li>
                            <li><a href="login-register.html">How It Works</a></li>
                            <li><a href="create-item.html">Create</a></li>
                            <li><a href="nft-marketplace.html">Explore</a></li>
                            <li><a href="login-register.html">Privacy & Terms</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer-widget">
                        <h4 class="fw-title">Community</h4>
                        <ul class="fw-links">
                            <li><a href="login-register.html">Help Center</a></li>
                            <li><a href="login-register.html">Partners</a></li>
                            <li><a href="login-register.html">Suggestions</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="login-register.html">Newsletter</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6">
                    <div class="footer-widget">
                        <h4 class="fw-title">Subscribe Us</h4>
                        <form action="#" class="newsletter-form">
                            <input type="email" placeholder="info@youmail.com">
                            <button type="submit"><i class="flaticon-small-rocket-ship-silhouette"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-wrap">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="copyright-text">
                        <p>All rights reserved © 2022 by <a href="#">ThemeBeyond</a></p>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="copyright-link-list">
                        <li><a href="login-register.html">Privacy Policy</a></li>
                        <li><a href="login-register.html">Terms And Condition</a></li>
                        <li><a href="login-register.html">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer-area-end -->

templates/meny/meny.sprava.html
{% load static %}

<div class="offcanvas-wrapper">
    <div class="menu-trigger"><i class="fi-sr-angle-small-left"></i></div>
    <div class="menu-close"><i class="fi-sr-angle-small-right"></i></div>
    <div class="offcanvas-inner scroll">
        <div class="author-profile text-center mb-30">
            <div class="author-img">
                <img src="assets/img/others/author_img.png" alt="">
            </div>
            <div class="author-content">
                <h4 class="title">Author Profile</h4>
                <p>Super Author</p>
                <a href="login-register.html" class="btn">Checkout</a>
            </div>
        </div>
        <div class="sidebar-slider text-center mb-25">
            <div class="sidebar-active">
                <div class="sidebar-img">
                    <a href="market-single.html"><img src="assets/img/others/sidebar_img01.png" alt=""></a>
                </div>
                <div class="sidebar-img">
                    <a href="market-single.html"><img src="assets/img/others/sidebar_img02.png" alt=""></a>
                </div>
                <div class="sidebar-img">
                    <a href="market-single.html"><img src="assets/img/others/sidebar_img03.png" alt=""></a>
                </div>
            </div>
        </div>
        <div class="overview">
            <div class="overview-title">
                <h4 class="title">Overview</h4>
            </div>
            <div class="overview-item-wrap">
                <div class="overview-item">
                    <div class="overview-icon">
                        <i class="fi-sr-box-alt"></i>
                    </div>
                    <div class="overview-content">
                        <h4 class="title">Open project</h4>
                        <span>820</span>
                    </div>
                    <a href="nft-marketplace.html"><i class=" fi-sr-angle-small-right"></i></a>
                </div>
                <div class="overview-item">
                    <div class="overview-icon">
                        <i class="fi-sr-mountains"></i>
                    </div>
                    <div class="overview-content">
                        <h4 class="title">Successful Completed</h4>
                        <span>546</span>
                    </div>
                    <a href="nft-marketplace.html"><i class=" fi-sr-angle-small-right"></i></a>
                </div>
                <div class="overview-item">
                    <div class="overview-icon">
                        <i class=" fi-sr-hourglass-end"></i>
                    </div>
                    <div class="overview-content">
                        <h4 class="title">trending</h4>
                        <span>32</span>
                    </div>
                    <a href="nft-marketplace.html"><i class=" fi-sr-angle-small-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="offcanvas-overly"></div>

templates/meny/meny.verh.html
{% load static %}

<!-- МЕНЮ ВЕРХНЕЕ-->
<header>
    <div class="menu-area">
        <div class="col-12">
            <div class="mobile-nav-toggler"><i class="fas fa-bars"></i></div>
            <!-- МЕНЮ ВЕРХНЕЕ-->
            <div class="menu-wrap">
                <nav class="menu-nav">
                    <!-- ЛОГОТИП С ПОИСКОМ-->
                    <div class="logo">
                        <a href="{% url 'Home:home' %}">
                            {% if site_settings.logo %}
                            <img src="{{ site_settings.logo.url }}" alt="{{ site_name }}" style="max-height: 50px;">
                            {% else %}
                            <img src="{% static 'nlp/img/logo/logo2.png' %}" alt="{{ site_name }}" style="max-height: 50px;">
                            {% endif %}
                        </a>
                    </div>
                    <div class="header-form">
                        <form action="#">
                            <button><i class="flaticon-search"></i></button>
                            <input type="text" placeholder="Search Artwork">
                        </form>
                    </div>
                    <!-- ЛОГОТИП С ПОИСКОМ-->
                    <!-- МЕНЮ ВЕРХНЕЕ-->
                    <div class="navbar-wrap main-menu d-none d-lg-flex">
                        <ul class="navigation">
                            <li class="active"><a href="{% url 'Home:home' %}">Главная</a></li>
                            <li><a href="{% url 'Archive:index' %}">Архив</a></li>
                            <li><a href="collections.html">Галлерея</a></li>
                            <li class="menu-item-has-children"><a href="#">Содержание</a>
                                <ul class="submenu">
                                    <li><a href="activity.html">Activity</a></li>
                                    <li><a href="category.html">Category</a></li>
                                    <li><a href="ranking.html">Ranking</a></li>
                                    
                                </ul>
                            </li>
                            <li class="menu-item-has-children"><a href="#">Blog</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'Blog:index' %}">Наш блог</a></li>
                                    <li><a href="{% url 'Blog:post_list' %}">Все посты</a></li>
                                    <li><a href="{% url 'Blog:category_list' %}">Категории</a></li>
                                    <li><a href="{% url 'Blog:tag_list' %}">Теги</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="header-action d-none d-md-block">
                        <ul>
                            {% if user.is_authenticated %}
                                <!-- Пользователь авторизован -->
                                <li class="header-user-info">
                                    <div class="dropdown">
                                        <a href="#" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                            👤 {{ user.username }}
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="{% url 'Blog:dashboard' %}">🏠 Личный кабинет</a></li>
                                            <li><a class="dropdown-item" href="{% url 'Blog:edit_profile' %}">✏️ Редактировать профиль</a></li>
                                            <li><a class="dropdown-item" href="{% url 'Blog:post_create' %}">➕ Создать пост</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href="{% url 'Blog:logout' %}">🚪 Выход</a></li>
                                        </ul>
                                    </div>
                                </li>
                            {% else %}
                                <!-- Пользователь не авторизован -->
                                <li class="header-btn"><a href="{% url 'Blog:login' %}" class="btn">🔐 Вход</a></li>
                                <li class="header-btn"><a href="{% url 'Blog:register' %}" class="btn btn-primary">📝 Регистрация</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>
            <!-- МЕНЮ ВЕРХНЕЕ-->

            <!-- Mobile Menu  -->
            <div class="mobile-menu">
                <nav class="menu-box">
                    <div class="close-btn"><i class="fas fa-times"></i></div>
                    <div class="nav-logo"><a href="{% url 'Home:home' %}"><img src="{% static 'nlp/img/logo/logo.png' %}" alt=""></a>
                    </div>
                    <div class="menu-outer">
                        <!--Здесь меню появится автоматически через Javascript / То же меню, что и в заголовке-->
                    </div>
                    <div class="social-links">
                        <ul class="clearfix">
                            <li><a href="#"><span class="fab fa-twitter"></span></a></li>
                            <li><a href="#"><span class="fab fa-facebook-f"></span></a></li>
                            <li><a href="#"><span class="fab fa-pinterest-p"></span></a></li>
                            <li><a href="#"><span class="fab fa-instagram"></span></a></li>
                            <li><a href="#"><span class="fab fa-youtube"></span></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="menu-backdrop"></div>
            <!-- End Mobile Menu -->
            
        </div>
    </div>
</header>

templates/meny/sidebar.html
{% load static %}

<!-- sidebar -->
<div class="sidebar">
    <div class="sidebar-logo mb-25">
        <a href="{% url 'Home:home' %}"><img src="{% static 'nlp/img/logo/logo.png' %}" alt=""></a>
    </div>
    <div class="sidebar-icon">
        <ul>
            <li class="active"><a href="{% url 'Home:home' %}"><i class="fi-sr-home"></i></a></li>
            <li><a href="{% url 'Archive:index' %}"><i class="fi-sr-archive"></i></a></li>
            <li><a href="collections.html"><i class="fi-sr-butterfly"></i></a></li>
            <li><a href="{% url 'Blog:index' %}"><i class="fi-sr-book-alt"></i></a></li>
            <li><a href="category.html"><i class="fi-sr-book"></i></a></li>
            <li><a href="category.html"><i class="fi-sr-crown"></i></a></li>
            <li><a href="author-profile.html"><i class="fi-sr-settings"></i></a></li>
            <li><a href="author-profile.html"><i class="fi-sr-user"></i></a></li>
            <li><a href="#" id="btnFullscreen"><i class="fi-sr-tool-marquee"></i></a></li>
        </ul>
    </div>
</div>
<!-- sidebar-fi-sr-book-alt end <i class="fi-sr-user">-->

templates/meny/sidibar-detail.html
<!-- СИДИБАР МЕНЮ -->
<div class="col-xxl-3 col-lg-4">

    <aside class="blog-sidebar">


        <div class="widget">
            <h4 class="sidebar-title">Search</h4>
            <div class="sidebar-search">
                <form action="#">
                    <input type="text" placeholder="Search ...">
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>


        <div class="widget">
            <h4 class="sidebar-title">Categories</h4>
            <div class="sidebar-cat-list">
                <ul>
                    <li><a href="#">Domain Names <i class="fas fa-angle-double-right"></i></a></li>
                    <li><a href="#">Photography <i class="fas fa-angle-double-right"></i></a></li>
                    <li><a href="#">Coinbase <i class="fas fa-angle-double-right"></i></a></li>
                    <li><a href="#">Trading Cards <i class="fas fa-angle-double-right"></i></a></li>
                </ul>
            </div>
        </div>


        <div class="widget">
            <h4 class="sidebar-title">Recent Post</h4>
            <div class="rc-post-list">
                <ul>
                    <li>
                        <div class="rc-post-thumb">
                            <a href="blog-details.html"><img src="assets/img/blog/rc_post_thumb01.jpg" alt=""></a>
                        </div>
                        <div class="rc-post-content">
                            <ul class="standard-blog-meta">
                                <li><a href="#"><i class="flaticon-avatar"></i>Admin</a></li>
                                <li><a href="#"><i class="flaticon-calendar"></i>Mar 10, 2022</a></li>
                            </ul>
                            <h5 class="title"><a href="blog-details.html">Marketplace is the online shop for the video</a></h5>
                        </div>
                    </li>
                    <li>
                        <div class="rc-post-thumb">
                            <a href="blog-details.html"><img src="assets/img/blog/rc_post_thumb02.jpg" alt=""></a>
                        </div>
                        <div class="rc-post-content">
                            <ul class="standard-blog-meta">
                                <li><a href="#"><i class="flaticon-avatar"></i>Admin</a></li>
                                <li><a href="#"><i class="flaticon-calendar"></i>Mar 10, 2022</a></li>
                            </ul>
                            <h5 class="title"><a href="blog-details.html">Marketplace is the online shop for the video</a></h5>
                        </div>
                    </li>
                </ul>
            </div>
        </div>


    </aside>
</div>
<!-- СИДИБАР МЕНЮ -->